### ISSUE TITLE
File Produced by BridgeGenerator is Invalid

### ISSUE THREAD

**Issue by Tony-Pappas** [ValdemarOrn/SharpSoundDevice#2]
Using VS 2015, I followed the instructions in Readme.md file and was able to build the SharpSoundDevice.sln, but the Build.XXX.dll file produced by the BridgeGenerator isn't seen by VST host applications. Is the header incorrect?

**Comment by ValdemarOrn** [comment]
Hi Tony. I strongly suspect an architecture mismatch (32 bit vs 64 bit) The current instructions state that the platform is only tested for 32 bit plugins and hosts, however my most recent version is working fine on 64 bit. I'll have to investigate whether the current version on Github has the necessary support for 64 bit, but I suspect it does and the docs are out of date.

In the meantime, please try and confirm that your plugin architecture matches your VST host. If you're running a 32 bit host then the default setting in the Visual studio solution should be fine, it should be set to Win32 / x86. To confirm, right click the solution at the top of the solution manager in Visual Studio, and choose "Configuration Manager". The "Active solution platform" should read x86 or Win32.

If you're using a 64 bit host, then you need to change the platform to 64 bit. Tutorials on how to get VS to build 64 bit code are available online, but the basic configuration change is listed here: https://msdn.microsoft.com/en-us/library/9yb4317s.aspx

In case it's not an architecture issue, I'll need to do some more debugging to figure out what is wrong, however I doubt I'll have enough time to provide proper assistance anytime soon.

**Comment by Tony-Pappas** [comment]
Hi Valdemar,

Thank you for responding.

I've tried both architectures (64 and 32) in both 64 and 32 bit hosts.

I've tried each of the previous versions of SharpSoundDevice (even found an old copy of VST 2.4)... nothing produces a dll that works in any of the hosts that I have. But your precompiled builds work excellent (i.e. SharpSoundDevice-Stable-1.4.2-2015-09-27) and it's a brilliant implementation.

Do you still have that particular VS solution? (Stable-1.4.2-2015-09-27)  If so, may a have a zipped copy? I may be able to find what's going on, by comparing my version to yours, then I could contribute the fixes.

I understand you're busy and I'd be willing to pay you for your help. If I can help in any way, testing, research, etc. please let me know, I'm ready to help in any way I can to get this project working.

**Comment by Faunsko** [comment]
To build a working bridge SharpSoundDevice.VST.dll you have to make two changes in the VST 2.4 SDK file vstpluginmain.cpp:

Add:
`#pragma unmanaged`

Replace the following line:
`#define VST_EXPORT`
with
`#define VST_EXPORT __declspec(dllexport)`
 to export the dll entry point.

**Comment by Tony-Pappas** [comment]
Faunsko, that fixed it. Thank you VERY MUCH for sharing that!!
