### ISSUE TITLE
$100 To Make This Work

### ISSUE THREAD

**Issue by Tony-Pappas** [ValdemarOrn/SharpSoundDevice#3]
I'll give $100 to the first person who can actually make this project build a valid VST (that'll run in FL Studio, Reason, etc.) in Visual Studio 2017 Community.

I've spent hours trying to get it to work. (I can get it to build, but the VST is invalid - it won't load in either FL Studio or Reason.)

Please help, I need the full solution (not just the dll) and I'm willing to pay you for it...

**Comment by williamsharkey** [comment]
Assuming your username is Tony, is there any content in the error log at: C:\Users\Tony\AppData\Roaming\SharpSoundDevice\Logs ?

**Comment by Tony-Pappas** [comment]
Hi, William, thank you for your response. No, there isn't an error in the log, because there is no log generated, as the VST host doesn't see the dll as a valid VST (so it never gets loaded).

**Comment by williamsharkey** [comment]
Can you please share a zipped folder of your vst so that I may test it on
my windows machine? Per the quickstart[1] guide, the included files should
be something like:

Bridge.SimplePlugin.dll
\SimplePlugin\SharpSoundDevice.dll
\SimplePlugin\SimplePlugin.dll
\SimplePlugin\AudioLib.dll

[1] https://github.com/ValdemarOrn/SharpSoundDevice/blob/master/Quickstart.md

**Comment by Tony-Pappas** [comment]
Here's the files that you requested (the debug output of my plugin project). I also included my VstPlugin Project and the SharpSoundDevice Solution.
[VstPluginDebugOutput.zip](https://github.com/ValdemarOrn/SharpSoundDevice/files/1175065/VstPluginDebugOutput.zip)
[VstPluginProject.zip](https://github.com/ValdemarOrn/SharpSoundDevice/files/1175066/VstPluginProject.zip)
[SharpSoundDeviceSolution.zip](https://github.com/ValdemarOrn/SharpSoundDevice/files/1175064/SharpSoundDeviceSolution.zip)

**Comment by Tony-Pappas** [comment]
No luck on finding a solution William?

**Comment by ValdemarOrn** [comment]
Please check out the latest tag, v1.5.0.1

It addresses several issues regarding loading and bootstrapping of the plugin. Most notably, you should get better crash logs when the host fails to load, and DllMain has been removed, which may have been the source of some unexpected problems and instability.

Edit: If problems persist, also ensure that you have the appropriate MSVC (Visual C runtime) installed. Links to them can be found in the updated readme.md
